<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Era;
use App\Models\Franchise;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CategorySuperSentaiSeeder extends Seeder
{
    public function run(): void
    {
        $showa = $this->Era('Showa');
        $heisei = $this->Era('Heisei');
        $reiwa = $this->Era('Reiwa');
        $supersentai = $this->Franchise('Super Sentai');

        $data = collect([
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Himitsu Sentai Gorenger',
                'name' => 'Gorenger',
                'slug' => Str::slug('Gorenger', '-'),
                'description' => 'Himitsu Sentai Gorenger (秘密戦隊ゴレンジャー, Himitsu Sentai Gorenjā; Secret Squadron Gorenger) is a Japanese tokusatsu superhero television series. Gorenger, created by Shotaro Ishinomori, was the 1st in the long-running Super Sentai metaseries of tokusatsu programming.',
                'img' => 'category/super-sentai-logo-1.webp',
                'first_aired' => '1975-04-05',
                'last_aired' => '1977-03-26',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Dengekitai J.A.K.Q.',
                'name' => 'J.A.K.Q.',
                'slug' => Str::slug('J.A.K.Q.', '-'),
                'description' => 'J.A.K.Q. Dengekitai (ジャッカー電撃隊, Jakkā Dengekitai; J.A.K.Q. Blitzkrieg), known in the Philippines as Lucky Aces, is a Japanese tokusatsu television show and the 2nd installment in the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-2.webp',
                'first_aired' => '1977-04-09',
                'last_aired' => '1977-12-24',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Battle Fever J',
                'name' => 'Fever J',
                'slug' => Str::slug('Fever J', '-'),
                'description' => 'Battle Fever J (バトルフィーバーJジェー, Batoru Fībā Jei) is a live-action tokusatsu TV series. The 3rd entry of the Super Sentai series franchise, Battle Fever J was produced by Toei Company in partnership with American comic book publisher Marvel Comics.',
                'img' => 'category/super-sentai-logo-3.webp',
                'first_aired' => '1979-02-03',
                'last_aired' => '1980-01-26',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Denshi Sentai Denjiman',
                'name' => 'Denjiman',
                'slug' => Str::slug('Denjiman', '-'),
                'description' => 'Denshi Sentai Denjiman (電子戦隊デンジマン; Electro Squadron Denjiman) is Toei\'s 4th entry to its Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-4.webp',
                'first_aired' => '1980-02-02',
                'last_aired' => '1981-01-31',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Taiyo Sentai Sun Vulcan',
                'name' => 'Sun Vulcan',
                'slug' => Str::slug('Sun Vulcan', '-'),
                'description' => 'Taiyo Sentai Sun Vulcan (太陽たい よう戦隊サンバルカン, Taiyō Sentai San Barukan; Solar Squadron Sun Vulcan) is a Japanese television show and the 5th series in Toei Company\'s Super Sentai tokusatsu metaseries.',
                'img' => 'category/super-sentai-logo-5.webp',
                'first_aired' => '1981-02-07',
                'last_aired' => '1982-01-30',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Dai Sentai Goggle V',
                'name' => 'Goggle V',
                'slug' => Str::slug('Goggle V', '-'),
                'description' => 'Dai Sentai Goggle-V (大戦隊ゴーグルファイブ, Dai Sentai Gōguru Faibu; Great Squadron Goggle-V) is a Japanese tokusatsu television series. It was the 6th installment in Toei Company\'s Super Sentai metaseries of tokusatsu television dramas.',
                'img' => 'category/super-sentai-logo-6.webp',
                'first_aired' => '1982-02-06',
                'last_aired' => '1983-01-29',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Kagaku Sentai Dynaman',
                'name' => 'Dynaman',
                'slug' => Str::slug('Dynaman', '-'),
                'description' => 'Kagaku Sentai Dynaman (科学戦隊ダイナマン, Kagaku Sentai Dainaman; Science Squadron Dynaman) is a Japanese tokusatsu television series and the 7th installment of Toei Company\'s Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-7.webp',
                'first_aired' => '1983-02-05',
                'last_aired' => '1984-01-28',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Choudenshi Bioman',
                'name' => 'Bioman',
                'slug' => Str::slug('Bioman', '-'),
                'description' => 'Choudenshi Bioman (Japanese: 超電子バイオマン, Hepburn: Chōdenshi Baioman; Super Electron Bioman) is a Japanese tokusatsu science fiction television series; Toei Company\'s 8th installment in the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-8.webp',
                'first_aired' => '1984-02-04',
                'last_aired' => '1985-01-26',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Dengeki Sentai Changeman',
                'name' => 'Changeman',
                'slug' => Str::slug('Changeman', '-'),
                'description' => 'Dengeki Sentai Changeman (電撃戦隊チェンジマン, Dengeki Sentai Chenjiman; Blitz Squadron Changeman) is a Japanese television series and the 9th installment of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-9.webp',
                'first_aired' => '1985-02-02',
                'last_aired' => '1986-02-22',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Choushinsei Flashman',
                'name' => 'Flashman',
                'slug' => Str::slug('Flashman', '-'),
                'description' => 'Choushinsei Flashman (超新星フラッシュマン, Chōshinsei Furasshuman; Supernova Flashman) is a Japanese television show broadcast on TV Asahi from 1986 to 1987. It was the 10th instalment in the Super Sentai metaseries produced by Toei Company, replacing Dengeki Sentai Changeman.',
                'img' => 'category/super-sentai-logo-10.webp',
                'first_aired' => '1986-03-01',
                'last_aired' => '1987-02-21',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Hikari Sentai Maskman',
                'name' => 'Maskman',
                'slug' => Str::slug('Maskman', '-'),
                'description' => 'Hikari Sentai Maskman (光戦隊マスクマン, Hikari Sentai Masukuman; Light Squadron Maskman) is a Japanese Tokusatsu television show and Toei\'s 11th entry of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-11.webp',
                'first_aired' => '1987-02-28',
                'last_aired' => '1988-02-20',
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'fullname' => 'Choujuu Sentai Liveman',
                'name' => 'Liveman',
                'slug' => Str::slug('Liveman', '-'),
                'description' => 'Choujyu Sentai Liveman (超獣戦隊ライブマン, Chōjū Sentai Raibuman; Super Beast Squadron Liveman) is a Japanese tokusatsu television series and the 12th entry of Toei Company\'s Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-12.webp',
                'first_aired' => '1988-02-27',
                'last_aired' => '1989-02-18',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Kousoku Sentai Turboranger',
                'name' => 'Turboranger',
                'slug' => Str::slug('Turboranger', '-'),
                'description' => 'Kousoku Sentai Turboranger (高速戦隊ターボレンジャー, Kōsoku Sentai Tāborenjā; High Speed Squadron Turboranger) is a Japanese television show and the 13th entry of Toei Company\'s Super Sentai metaseries and the first title of the Heisei period.',
                'img' => 'category/super-sentai-logo-13.webp',
                'first_aired' => '1989-03-04',
                'last_aired' => '1990-02-23',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Chikyuu Sentai Fiveman',
                'name' => 'Fiveman',
                'slug' => Str::slug('Fiveman', '-'),
                'description' => 'Chikyu Sentai Fiveman (地球戦隊ファイブマン, Chikyū Sentai Faibuman; Earth Squadron Fiveman) is a Japanese Tokusatsu television series. It was Toei Company\'s 14th installment of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-14.webp',
                'first_aired' => '1990-03-02',
                'last_aired' => '1991-02-08',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Choujin Sentai Jetman',
                'name' => 'Jetman',
                'slug' => Str::slug('Jetman', '-'),
                'description' => 'Chojin Sentai Jetman (鳥人戦隊ジェットマン, Chōjin Sentai Jettoman; Birdman Squadron Jetman) is a Japanese tokusatsu television series produced by Toei Company. It is the 15th entry of the Super Sentai metaseries, following the previous series Chikyu Sentai Fiveman.',
                'img' => 'category/super-sentai-logo-15.webp',
                'first_aired' => '1991-02-15',
                'last_aired' => '1992-02-14',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Kyouryuu Sentai Zyuranger',
                'name' => 'Zyuranger',
                'slug' => Str::slug('Zyuranger', '-'),
                'description' => 'Kyōryū Sentai Zyuranger (Japanese: 恐竜戦隊ジュウレンジャー, Hepburn: Kyōryū Sentai Juurenjā; Dinosaur Squadron Zyuranger) is a Japanese tokusatsu television series and the 16th installment in the long-running Super Sentai metaseries of superhero programs.',
                'img' => 'category/super-sentai-logo-16.webp',
                'first_aired' => '1992-02-21',
                'last_aired' => '1993-02-12',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Gosei Sentai Dairanger',
                'name' => 'Dairanger',
                'slug' => Str::slug('Dairanger', '-'),
                'description' => 'Gosei Sentai Dairanger (五星戦隊ダイレンジャー, Gosei Sentai Dairenjā; Five Stars Squadron Dairanger) is a Japanese tokusatsu television series. It was the 17th production in the long-running Super Sentai metaseries of television tokusatsu dramas produced by Toei Company, following Kyōryū Sentai Zyuranger.',
                'img' => 'category/super-sentai-logo-17.webp',
                'first_aired' => '1993-02-19',
                'last_aired' => '1994-02-11',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Ninja Sentai Kakuranger',
                'name' => 'Kakuranger',
                'slug' => Str::slug('Kakuranger', '-'),
                'description' => 'Ninja Sentai Kakuranger (忍者戦隊カクレンジャー, Ninja Sentai Kakurenjā; Ninja Squadron Kakuranger) is a Japanese tokusatsu television series. It was Toei Company Limited\'s 18th production of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-18.webp',
                'first_aired' => '1994-02-18',
                'last_aired' => '1995-02-24',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Choriki Sentai Ohranger',
                'name' => 'Ohranger',
                'slug' => Str::slug('Ohranger', '-'),
                'description' => 'Chouriki Sentai Ohranger (超力戦隊オーレンジャー, Chōriki Sentai Ōrenjā; Super-Powered Squadron Ohranger) is a Japanese tokusatsu television series and the 19th installment in the long-running Super Sentai metaseries of superhero programs and celebrated the franchise\'s 20th anniversary.',
                'img' => 'category/super-sentai-logo-19.webp',
                'first_aired' => '1995-03-03',
                'last_aired' => '1996-02-23',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Gekisou Sentai Carranger',
                'name' => 'Carranger',
                'slug' => Str::slug('Carranger', '-'),
                'description' => 'Gekisou Sentai Carranger (激走戦隊カーレンジャー, Gekisō Sentai Kārenjā; Racing Squadron Carranger) is a Japanese tokusatsu television show. It was Toei\'s 20th production of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-20.webp',
                'first_aired' => '1996-03-01',
                'last_aired' => '1997-02-07',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Denji Sentai Megaranger',
                'name' => 'Megaranger',
                'slug' => Str::slug('Megaranger', '-'),
                'description' => 'Denji Sentai Megaranger (電磁戦隊メガレンジャー, Denji Sentai Megarenjā; Electromagnetic Squadron Megaranger) is Toei\'s 21st production of the Super Sentai metaseries, and the second Sentai, after Kousoku Sentai Turboranger in which all heroes are high school students.',
                'img' => 'category/super-sentai-logo-21.webp',
                'first_aired' => '1997-02-14',
                'last_aired' => '1998-02-15',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Seijuu Sentai Gingaman',
                'name' => 'Gingaman',
                'slug' => Str::slug('Gingaman', '-'),
                'description' => 'Seijuu Sentai Gingaman (星獣戦隊ギンガマン, Seijū Sentai Gingaman; Star Beast Squadron Gingaman) is a Japanese tokusatsu television series. It is Toei\'s 22nd entry of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-22.webp',
                'first_aired' => '1998-02-22',
                'last_aired' => '1999-02-14',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Kyukyu Sentai GoGoFive',
                'name' => 'GoGoFive',
                'slug' => Str::slug('GoGoFive', '-'),
                'description' => 'Kyuukyuu Sentai GoGoFive (救急戦隊ゴーゴーファイブ, Kyūkyū Sentai Gōgō Faibu; Rescue Squadron GoGoFive) is a Japanese Tokusatsu television series and the 23rd entry of the long-running Japanese Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-23.webp',
                'first_aired' => '1999-02-21',
                'last_aired' => '2000-02-06',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Mirai Sentai Timeranger',
                'name' => 'Timeranger',
                'slug' => Str::slug('Timeranger', '-'),
                'description' => 'Mirai Sentai Timeranger (未来戦隊タイムレンジャー, Mirai Sentai Taimurenjā; Future Squadron Timeranger) is a Japanese tokusatsu television series and the 24th series in Toei\'s Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-24.webp',
                'first_aired' => '2000-02-13',
                'last_aired' => '2001-02-11',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Hyakuju Sentai Gaoranger',
                'name' => 'Gaoranger',
                'slug' => Str::slug('Gaoranger', '-'),
                'description' => 'Hyakujuu Sentai Gaoranger (百獣戦隊ガオレンジャー, Hyakujū Sentai Gaorenjā; Hundred Beasts Squadron Gaoranger) is a Japanese Tokusatsu television series and Toei\'s 25th production of the Super Sentai metaseries airing in 2001 and celebrated the franchise\'s 25th anniversary.',
                'img' => 'category/super-sentai-logo-25.webp',
                'first_aired' => '2001-02-18',
                'last_aired' => '2002-02-10',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Ninpuu Sentai Hurricaneger',
                'name' => 'Hurricaneger',
                'slug' => Str::slug('Hurricaneger', '-'),
                'description' => 'Ninpuu Sentai Hurricaneger (忍風戦隊ハリケンジャー, Ninpū Sentai Harikenjā; Wind Ninja Squadron Hurricaneger) is a Japanese Tokusatsu television show and Toei\'s 26th production of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-26.webp',
                'first_aired' => '2002-02-17',
                'last_aired' => '2003-02-09',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Bakuryuu Sentai Abaranger',
                'name' => 'Abaranger',
                'slug' => Str::slug('Abaranger', '-'),
                'description' => 'Bakuryū Sentai Abaranger (爆竜戦隊アバレンジャー, Bakuryū Sentai Abarenjā; Burstosaur Squadron Abaranger) is a Japanese Tokusatsu television show and Toei\'s 27th production of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-27.webp',
                'first_aired' => '2003-02-16',
                'last_aired' => '2004-02-08',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Tokusou Sentai Dekaranger',
                'name' => 'Dekaranger',
                'slug' => Str::slug('Dekaranger', '-'),
                'description' => 'Tokusou Sentai Dekaranger (特捜戦隊デカレンジャー, Tokusō Sentai Dekarenjā; Special Police Squadron Dekaranger) is a Japanese Tokusatsu television show and the 28th production of the Super Sentai metaseries produced by Toei.',
                'img' => 'category/super-sentai-logo-28.webp',
                'first_aired' => '2004-02-15',
                'last_aired' => '2005-02-06',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Mahou Sentai Magiranger',
                'name' => 'Magiranger',
                'slug' => Str::slug('Magiranger', '-'),
                'description' => 'Mahō Sentai Magiranger (魔法戦隊マジレンジャー, Mahō Sentai Majirenjā; Magical Squadron Magiranger) is a Japanese Tokusatsu television show and Toei Company\'s 29th production of the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-29.webp',
                'first_aired' => '2005-02-13',
                'last_aired' => '2006-02-12',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Gougou Sentai Boukenger',
                'name' => 'Boukenger',
                'slug' => Str::slug('Boukenger', '-'),
                'description' => 'GoGo Sentai Boukenger (轟轟戦隊ボウケンジャー, Gōgō Sentai Bōkenjā; Rumbling Squadron Boukenger) is the 30th series in Toei\'s Super Sentai series, a metaseries of Japanese tokusatsu programming and celebrated the franchise\'s 30th anniversary.',
                'img' => 'category/super-sentai-logo-30.webp',
                'first_aired' => '2006-02-19',
                'last_aired' => '2007-02-11',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Juken Sentai Gekiranger',
                'name' => 'Gekiranger',
                'slug' => Str::slug('Gekiranger', '-'),
                'description' => 'Juken Sentai Gekiranger (獣拳戦隊ゲキレンジャー, Jūken Sentai Gekirenjā; Beast Fist Squadron Gekiranger) is Toei Company\'s 31st entry in the Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-31.webp',
                'first_aired' => '2007-02-18',
                'last_aired' => '2008-02-10',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Engine Sentai Go-Onger',
                'name' => 'Go-Onger',
                'slug' => Str::slug('Go-Onger', '-'),
                'description' => 'Engine Sentai Go-onger (炎神戦隊ゴーオンジャー, Enjin Sentai Gōonjā; Engine Squadron Go-onger) is Toei Company\'s 32nd installment in the Super Sentai metaseries of Japanese tokusatsu television series.',
                'img' => 'category/super-sentai-logo-32.webp',
                'first_aired' => '2008-02-17',
                'last_aired' => '2009-02-08',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Samurai Sentai Shinkenger',
                'name' => 'Shinkenger',
                'slug' => Str::slug('Shinkenger', '-'),
                'description' => 'Samurai Sentai Shinkenger (侍戦隊シンケンジャー, Samurai Sentai Shinkenjā; Samurai Squadron Shinkenger) is the title of Toei Company\'s 33rd entry in its long-running Super Sentai metaseries of Japanese tokusatsu television series.',
                'img' => 'category/super-sentai-logo-33.webp',
                'first_aired' => '2009-02-15',
                'last_aired' => '2010-02-07',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Tensou Sentai Goseiger',
                'name' => 'Goseiger',
                'slug' => Str::slug('Goseiger', '-'),
                'description' => 'Tensou Sentai Goseiger (天装戦隊ゴセイジャー, Tensō Sentai Goseijā; Heavenly Armament Squadron Goseiger) is the title of Toei Company\'s 34th entry in its long-running Super Sentai franchise.',
                'img' => 'category/super-sentai-logo-34.webp',
                'first_aired' => '2010-02-14',
                'last_aired' => '2011-02-06',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Kaizoku Sentai Gokaiger',
                'name' => 'Gokaiger',
                'slug' => Str::slug('Gokaiger', '-'),
                'description' => 'Kaizoku Sentai Gokaiger (海賊戦隊ゴーカイジャー, Kaizoku Sentai Gōkaijā; Pirate Squadron Gokaiger) is a Japanese Tokusatsu television series and the 35th entry in its long-running Super Sentai metaseries of Japanese tokusatsu and celebrated the franchise\'s 35th anniversary.',
                'img' => 'category/super-sentai-logo-35.webp',
                'first_aired' => '2011-02-13',
                'last_aired' => '2012-02-19',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Tokumei Sentai Go-Busters',
                'name' => 'Go-Busters',
                'slug' => Str::slug('Go-Busters', '-'),
                'description' => 'Tokumei Sentai Go-Busters (特命戦隊ゴーバスターズ, Tokumei Sentai Gōbasutāzu; Special Operations Squadron Go-Busters) is a Japanese tokusatsu television series and the 36th entry in Toei Company\'s Super Sentai metaseries, following Kaizoku Sentai Gokaiger.',
                'img' => 'category/super-sentai-logo-36.webp',
                'first_aired' => '2012-02-26',
                'last_aired' => '2013-02-10',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Zyuden Sentai Kyoryuger',
                'name' => 'Kyoryuger',
                'slug' => Str::slug('Kyoryuger', '-'),
                'description' => 'Zyuden Sentai Kyoryuger (獣電戦隊キョウリュウジャー, Jūden Sentai Kyōryūjā; Electrobeast Squadron Kyoryuger) is Toei Company\'s 37th entry in its long-running Super Sentai metaseries of Japanese tokusatsu television series aired on TV Asahi from 17 February 2013 to 9 February 2014, replacing Tokumei Sentai Go-Busters and was replaced by Ressha Sentai ToQger.',
                'img' => 'category/super-sentai-logo-37.webp',
                'first_aired' => '2013-02-17',
                'last_aired' => '2014-02-09',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Ressha Sentai ToQger',
                'name' => 'ToQger',
                'slug' => Str::slug('ToQger', '-'),
                'description' => 'Ressha Sentai ToQger (烈車戦隊トッキュウジャー, Ressha Sentai Tokkyūjā; Train Squadron ToQger) is a Japanese television series, a Tokusatsu drama of the 38th installment in Toei Company\'s Super Sentai metaseries, following Zyuden Sentai Kyoryuger.',
                'img' => 'category/super-sentai-logo-38.webp',
                'first_aired' => '2014-02-16',
                'last_aired' => '2015-02-15',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Shuriken Sentai Ninninger',
                'name' => 'Ninninger',
                'slug' => Str::slug('Ninninger', '-'),
                'description' => 'Shuriken Sentai Ninninger (手裏剣戦隊ニンニンジャー, Shuriken Sentai Ninninjā; Shuriken Squadron Ninninger) is a Japanese television series, the 39th entry of Toei\'s long-running Super Sentai metaseries, following Ressha Sentai ToQger.',
                'img' => 'category/super-sentai-logo-39.webp',
                'first_aired' => '2015-02-22',
                'last_aired' => '2016-02-07',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Doubutsu Sentai Zyuohger',
                'name' => 'Zyuohger',
                'slug' => Str::slug('Zyuohger', '-'),
                'description' => 'Doubutsu Sentai Zyuohger (動物戦隊ジュウオウジャー, Dōbutsu Sentai Jūōjā; Animal Squadron Zyuohger) is a Japanese Tokusatsu drama and the 40th entry of Toei\'s long-running Super Sentai metaseries, following Shuriken Sentai Ninninger. ',
                'img' => 'category/super-sentai-logo-40.webp',
                'first_aired' => '2016-02-14',
                'last_aired' => '2017-02-05',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Uchuu Sentai Kyuuranger',
                'name' => 'Kyuuranger',
                'slug' => Str::slug('Kyuuranger', '-'),
                'description' => 'Uchu Sentai Kyuranger (宇宙戦隊キュウレンジャー, Uchū Sentai Kyūrenjā; Space Squadron Kyuranger) is a Japanese tokusatsu drama and the 41st entry of Toei\'s long-running Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-41.webp',
                'first_aired' => '2017-02-12',
                'last_aired' => '2018-02-04',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Kaitou Sentai Lupinranger vs Keisatsu Sentai Patranger',
                'name' => 'Lupinranger vs Patranger',
                'slug' => Str::slug('Lupinranger vs Patranger', '-'),
                'description' => 'Kaitou Sentai Lupinranger VS Keisatsu Sentai Patranger (快盗戦隊ルパンレンジャーVS警察戦隊パトレンジャー, Kaitō Sentai Rupanrenjā Bui Esu Keisatsu Sentai Patorenjā; Phantom Thief Squadron Lupinranger VS Police Squadron Patranger), commonly shortened as LuPat (ルパパト, Rupapato), is a Japanese tokusatsu drama and the 42nd entry of the Toei Company\'s long-running Super Sentai metaseries.',
                'img' => 'category/super-sentai-logo-42-43.webp',
                'first_aired' => '2018-02-11',
                'last_aired' => '2019-02-10',
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'fullname' => 'Kishiryu Sentai Ryusoulger',
                'name' => 'Ryusoulger',
                'slug' => Str::slug('Ryusoulger', '-'),
                'description' => 'Kishiryu Sentai Ryusoulger (騎士竜戦隊リュウソウジャー, Kishiryū Sentai Ryūsōjā; Knightosaur Squadron Ryusoulger) is a Japanese tokusatsu drama and the 43rd entry of the Toei Company\'s long-running Super Sentai series.',
                'img' => 'category/super-sentai-logo-44.webp',
                'first_aired' => '2019-03-17',
                'last_aired' => '2020-03-01',
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'fullname' => 'Mashin Sentai Kiramager',
                'name' => 'Kiramager',
                'slug' => Str::slug('Kiramager', '-'),
                'description' => 'Mashin Sentai Kiramager (魔進戦隊キラメイジャー, Mashin Sentai Kirameijā; Machine Squadron Kiramager) is a Japanese tokusatsu drama. It is the 44th entry of Toei\'s long-running Super Sentai metaseries and the first series to air exclusively in the Reiwa era.',
                'img' => 'category/super-sentai-logo-45.webp',
                'first_aired' => '2020-03-08',
                'last_aired' => '2021-02-28',
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'fullname' => 'Kikai Sentai Zenkaiger',
                'name' => 'Zenkaiger',
                'slug' => Str::slug('Zenkaiger', '-'),
                'description' => 'Kikai Sentai Zenkaiger (機界戦隊ゼンカイジャー, Kikai Sentai Zenkaijā; Mecha World Squadron Zenkaiger) is a Japanese tokusatsu television series, the 45th entry in Toei\'s long-running Super Sentai series, and the second produced in the Reiwa era.',
                'img' => 'category/super-sentai-logo-46.webp',
                'first_aired' => '2021-03-07',
                'last_aired' => '2022-02-27',
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'fullname' => 'Avataro Sentai Donbrothers',
                'name' => 'Donbrothers',
                'slug' => Str::slug('Donbrothers', '-'),
                'description' => 'Avataro Sentai Donbrothers (暴太郎戦隊ドンブラザーズ, Abatarō Sentai Donburazāzu; Avataro Squadron Donbrothers) is a Japanese tokusatsu television dramedy, the 46th entry in Toei\'s long-running Super Sentai series and the third produced in the Reiwa era.',
                'img' => 'category/super-sentai-logo-47.webp',
                'first_aired' => '2022-03-06',
                'last_aired' => '2023-02-26',
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'fullname' => 'Ohsama Sentai King-Ohger',
                'name' => 'King-Ohger',
                'slug' => Str::slug('King-Ohger', '-'),
                'description' => 'Ohsama Sentai King-Ohger (王様戦隊キングオージャー, Ōsama Sentai Kinguōjā; Kingship Squadron King-Ohger) is a Japanese tokusatsu television drama, the 47th installment in Toei Company\'s long-running Super Sentai series and the fourth produced in the Reiwa era.',
                'img' => 'category/super-sentai-logo-48.webp',
                'first_aired' => '2023-03-05',
                'last_aired' => '2024-02-25',
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'fullname' => 'Bakuage Sentai Boonboomger',
                'name' => 'Boonboomger',
                'slug' => Str::slug('Boonboomger', '-'),
                'description' => 'Bakuage Sentai Boonboomger (爆上戦隊ブンブンジャー, Bakuage Sentai Bunbunjā; Explosive Squadron Boonboomger) is a Japanese Tokusatsu television series, the 48th installment in Toei Company\'s Super Sentai series, and the fifth produced in the Reiwa era.',
                'img' => 'category/super-sentai-logo-49.webp',
                'first_aired' => '2024-03-03',
                'last_aired' => '2025-02-09',
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'fullname' => 'No.1 Sentai Gozyuger',
                'name' => 'Gozyuger',
                'slug' => Str::slug('Gozyuger', '-'),
                'description' => 'No.1 Sentai Gozyuger (ナンバーワン戦隊ゴジュウジャー, Nanbā Wan Sentai Gojūjā; Number One Squadron Gozyuger) is a Japanese Tokusatsu drama, the 49th installment in Toei Company\'s Super Sentai series, the sixth produced in the Reiwa era, and a commemoration of the 50th anniversary of the franchise.',
                'img' => 'category/super-sentai-logo-50.webp',
                'first_aired' => '2025-02-16',
                'last_aired' => null,
            ],
        ]);

        foreach ($data as $item) {
            Category::create($item);
        }
    }

    private function Era(string $name): string
    {
        $era = Era::where('name', $name)->first();
        if (!$era) {
            $era = Era::create([
                'name' => $name,
            ]);
        }
        return $era->id;
    }

    private function Franchise(string $name): string
    {
        $franchise = Franchise::where('name', $name)->first();
        if (!$franchise) {
            $franchise = Franchise::create([
                'name' => $name,
            ]);
        }
        return $franchise->id;
    }
}
