<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Era;
use App\Models\Franchise;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Carbon;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $showa = $this->Era('Showa');
        $heisei = $this->Era('Heisei');
        $reiwa = $this->Era('Reiwa');
        $ultraman = $this->Franchise('Ultraman');
        $kamenrider = $this->Franchise('Kamen Rider');
        $supersentai = $this->Franchise('Super Sentai');

        $data = collect([
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Kamen Rider',
                'slug' => Str::slug('Kamen Rider', '-'),
                'description' => 'Kamen Rider (仮面ライダー, Kamen Raidā, "Masked Rider"), is a Japanese tokusatsu drama and the first installment in what would be known as the Kamen Rider Series. It is the first entry of the Showa Era and aired from April 3, 1971 to February 10, 1973 on the Mainichi Broadcasting System and NET TV (now TV Asahi). With 98 episodes, it is the longest entry of the franchise to date.',
                'img' => "kamen-rider/showa/0.1-ichigo-nigo-riders-1.jpg",
                'first_aired' => '1971-04-03',
                'last_aired' => '1973-02-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'V3',
                'slug' => Str::slug('V3', '-'),
                'description' => 'Kamen Rider V3 (仮面ライダーV3ブイスリー, Kamen Raidā Bui Surī, "Masked Rider V3" in English), is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the second series to debut in the Showa Era, serving as a direct sequel to the original Kamen Rider. A joint collaboration between Ishimori Productions and Toei, the series aired from February 17, 1973 to February 9, 1974 on the Mainichi Broadcasting System and NET TV (now TV Asahi), with a total of 52 episodes.',
                'img' => "kamen-rider/showa/0.2-v3-riderman-riders-1.jpg",
                'first_aired' => '1973-02-17',
                'last_aired' => '1974-02-09',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Rider X',
                'slug' => Str::slug('Rider X', '-'),
                'description' => 'Kamen Rider X (仮面ライダーＸエックス, Kamen Raidā Ekkusu, translated as "Masked Rider X") is a Japanese tokusatsu drama and the third installment of the Kamen Rider Series. It is the third series to debut during the Showa Era and aired from February 16, 1974 to October 12, 1974 for 35 episodes on NET (now known as TV Asahi).',
                'img' => "kamen-rider/showa/0.3-x-rider.jpg",
                'first_aired' => '1974-02-16',
                'last_aired' => '1974-10-12',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Amazon',
                'slug' => Str::slug('Amazon', '-'),
                'description' => 'Kamen Rider Amazon (仮面ライダーアマゾン, Kamen Raidā Amazon, "Masked Rider Amazon" in English) is a Japanese tokusatsu drama and the fourth installment of the Kamen Rider Series. It is the fourth series to debut in the Showa Era and aired from October 19, 1974 to March 29, 1975 on NET and the Mainichi Broadcasting System. With 24 episodes produced and aired, it is the shortest Kamen Rider series ever.',
                'img' => "kamen-rider/showa/0.4-amazon-rider-1.jpg",
                'first_aired' => '1974-10-19',
                'last_aired' => '1975-03-29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Stronger',
                'slug' => Str::slug('Stronger', '-'),
                'description' => 'Kamen Rider Stronger (仮面ライダーストロンガー, Kamen Raidā Sutorongā, "Masked Rider Stronger" in English) is a Japanese tokusatsu drama and the fifth installment of the Kamen Rider Series. It is the fifth series to debut in the Showa Era and aired from April 5, 1975 to December 27, 1975 on TBS and MBS. Lasting 39 episodes, the series was a joint collaboration between Toei Company and Ishinomori Productions.',
                'img' => "kamen-rider/showa/0.5-stronger-rider-1.jpg",
                'first_aired' => '1975-04-05',
                'last_aired' => '1975-12-27',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Skyrider',
                'slug' => Str::slug('Skyrider', '-'),
                'description' => 'Kamen Rider (仮面ライダー, Kamen Raidā), also known as Skyrider (スカイライダー, Sukairaidā), is a Japanese tokusatsu television series created by Shotaro Ishinomori and the sixth program in the Kamen Rider Series. The series was produced by Toei Company. The series aired every Friday at 7:00 PM on MBS from October 5, 1979 to October 10, 1980.',
                'img' => "kamen-rider/showa/0.6-sky-rider-1.jpg",
                'first_aired' => '1979-10-05',
                'last_aired' => '1980-10-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Super-1',
                'slug' => Str::slug('Super-1', '-'),
                'description' => 'Kamen Rider Super-1 (仮面ライダースーパー１ワン, Kamen Raidā Sūpā Wan, Masked Rider Super-1 in English) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the seventh series to debut in the Showa era and aired as a joint collaboration between Toei Company and Ishinomori Productions from October 17, 1980 to October 3, 1981 for 48 episodes. The average ratings of the series was 9.9%.',
                'img' => "kamen-rider/showa/0.7-super1-rider-1.jpg",
                'first_aired' => '1980-10-17',
                'last_aired' => '1981-10-03',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'ZX',
                'slug' => Str::slug('ZX', '-'),
                'description' => 'Birth of the 10th! Kamen -riders All Together!! (10号誕生！仮面ライダー全員集合！！, Jūgō Tanjō! Kamen Raidā Zen\'in Shūgō!!) is a Japanese television special in Toei Company\'s Kamen Rider Series. It is the eighth entry of the Showa-era and premiered on January 3, 1984. The special follows Ryo Murasame, the tenth person to don the Kamen Rider title, as he fights against the Badan Empire who killed his sister.',
                'img' => "kamen-rider/showa/0.7-movie-10th-kamen-rider.jpg",
                'first_aired' => '1984-01-03',
                'last_aired' => '1984-01-03',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Black',
                'slug' => Str::slug('Black', '-'),
                'description' => 'Kamen Rider Black (仮面ライダーBLACKブラック, Kamen Raidā Burakku, translated as "Masked Rider Black"), is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the ninth series to debut in the Showa Era and aired as a joint collaboration between Ishimori Productions and Toei Company from October 4, 1987 to October 9, 1988 on MBS and the TBS for 51 episodes.',
                'img' => "kamen-rider/showa/0.8-black-riders-1.jpg",
                'first_aired' => '1987-10-04',
                'last_aired' => '1988-10-09',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Black RX',
                'slug' => Str::slug('Black RX', '-'),
                'description' => 'Kamen Rider Black RX (仮面ライダーBLACKブラック RXアールエックス, Kamen Raidā Burakku Āru Ekkusu, Masked Rider Black RX) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the tenth and final series to debut in the Showa Era and serves as a direct sequel to Kamen Rider Black. It aired as a joint collaboration between Ishimori Productions and Toei Company from October 23, 1988 to September 24, 1989 on MBS and the TBS for 47 episodes.',
                'img' => "kamen-rider/showa/0.9-black-rx-riders-1.jpg",
                'first_aired' => '1988-10-23',
                'last_aired' => '1989-09-24',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Shin',
                'slug' => Str::slug('Shin', '-'),
                'description' => 'Shin Kamen Rider: Prologue (真・仮面ライダー 序章プロローグ, Shin Kamen Raidā: Purorōgu, Lit. "True Masked Rider Prologue") is a Japanese superhero Tokusatsu V-Cinema film in the Kamen Rider Series, serving as the 11th production in the franchise while also commemorating the franchise\'s 20th anniversary. In the film, a young man is transformed into a mutant grasshopper while he is targeted by the mysterious Institute of Super Science.',
                'img' => "kamen-rider/showa/0.13-shin-rider.jpg",
                'first_aired' => '1992-02-20',
                'last_aired' => '1992-02-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'ZO',
                'slug' => Str::slug('ZO', '-'),
                'description' => 'Kamen Rider ZO (仮面ライダーZ Oゼットオー, Kamen Raidā Zetto Ō) is a Japanese superhero Tokusatsu film serving as the 12th installment of the Kamen Rider Series, triple-billed with film versions of Gosei-sentai-Dairanger and Tokusou Robo Janperson. In the film, a young man must protect the son of the doctor who experimented on him from a monster who threatens to wipe out humanity.',
                'img' => "kamen-rider/showa/0.14-zo-rider.jpg",
                'first_aired' => '1993-12-21',
                'last_aired' => '1993-12-21',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'J',
                'slug' => Str::slug('J', '-'),
                'description' => 'Kamen Rider J (仮面ライダーJ, Kamen Raidā Jei), translated as Masked Rider J, is a Japanese superhero tokusatsu film, serving as the 13th entry of the Kamen Rider series and was triple-billed with film versions of Ninja-sentai-Kakuranger and Blueswat.',
                'img' => "kamen-rider/showa/0.15-j-rider.jpg",
                'first_aired' => '1994-04-16',
                'last_aired' => '1994-04-16',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Kuuga",
                'slug' => Str::slug("Kuuga", '-'),
                'description' => "Kamen Rider Kuuga (仮面ライダークウガ Kamen Raidā Kūga, Masked Rider Kuuga) is a Japanese tokusatsu drama and the 10th installment of the Kamen Rider Series. Debuting as the first entry of the Heisei Era, the series aired from January 30, 2000 to January 21, 2001 on TV Asahi as a joint collaboration between Ishimori Productions and Toei Company.",
                'img' => "kamen-rider/heisei/1.kuuga/1.1-kuuga-rider-5.jpg",
                'first_aired' => '2000-01-30',
                'last_aired' => '2001-01-21',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Agito",
                'slug' => Str::slug("Agito", '-'),
                'description' => "Kamen Rider Agito (仮面ライダーアギト Kamen Raidā Agito, Masked Rider ΑGITΩ), is the eleventh installment in the popular Kamen Rider tokusatsu franchise. The series represented the 30th Anniversary of the Kamen Rider Series. The series was also a joint collaboration between Ishimori Productions and Toei and was shown on TV Asahi from January 28, 2001 to January 27, 2002. The catchphrase for the series is \"Awaken the soul\" (目覚めろ、その魂 Mezamero, sono tamashii).",
                'img' => "kamen-rider/heisei/2.agito/1.2-agito-riders-1.jpg",
                'first_aired' => '2001-01-28',
                'last_aired' => '2002-01-27',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Ryuki",
                'slug' => Str::slug("Ryuki", '-'),
                'description' => "Kamen Rider Ryuki (仮面ライダー龍騎 Kamen Raidā Ryūki, Masked Rider Ryuki) is a Japanese tokusatsu television series. It was the twelfth installment in the Kamen Rider Series of tokusatsu shows. It was a joint collaboration between Ishimori Productions and Toei, and it was shown on TV Asahi from February 3, 2002 to January 19, 2003. The catchphrase for the series is \"Those who don't fight won't survive!!\" (戦わなければ、生き残れない!! Tatakawanakereba, ikinokorenai!!). In 2009, Ryuki was adapted into the American television series Kamen Rider Dragon Knight, the first adaptation of a Kamen Rider Series in the United States since Saban's Masked Rider in 1996.",
                'img' => "kamen-rider/heisei/3.ryuki/1.3-ryuki-riders-2.jpg",
                'first_aired' => '2002-02-03',
                'last_aired' => '2003-01-19',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "555",
                'slug' => Str::slug("555", '-'),
                'description' => "Kamen Rider 555 (仮面ライダー555（ファイズ） Kamen Raidā Faizu, Masked Rider Φ's or Faiz or Phi's) is a Japanese tokusatsu television drama. It is the 13th installment in the Kamen Rider Series. It is a joint collaboration between Ishinomori Productions and Toei, and was broadcast on TV Asahi from January 26, 2003, to January 18, 2004. This series was the first to use TV Asahi's current logo. It aired as a part of TV Asahi's 2003 Super Hero Time block, alongside Bakuryū-sentai-Abaranger.",
                'img' => "kamen-rider/heisei/4.faiz/1.4-faiz-riders-1.jpg",
                'first_aired' => '2003-01-26',
                'last_aired' => '2004-01-18',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Blade",
                'slug' => Str::slug("Blade", '-'),
                'description' => "Kamen Rider Blade (仮面ライダー剣［ブレイド］ Kamen Raidā Bureido, Masked Rider ♠ or Blade), is a Japanese tokusatsu drama and the 14th installment of the Kamen Rider Series. Debuting as the 5th entry of the Heisei Era, the show premiered on January 25, 2004 alongside Tokusou-sentai-DekarangerIcon-crosswiki.png on TV Asahi's Super Hero Time block, and finished its 49-episode run on January 23, 2005.",
                'img' => "kamen-rider/heisei/5.blade/1.5-blade-riders-1.jpg",
                'first_aired' => '2004-01-25',
                'last_aired' => '2005-01-23',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Hibiki",
                'slug' => Str::slug("Hibiki", '-'),
                'description' => "Kamen Rider Hibiki (仮面ライダー響鬼［ヒビキ］ Kamen Raidā Hibiki, Masked Rider Hibiki) is a Japanese tokusatsu superhero television series. It is the fifteenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. Kamen Rider Hibiki first aired on January 30, 2005 and aired its final episode on January 22, 2006. It aired alongside Mahou-sentai-MagirangerIcon-crosswiki.png for Super Hero Time 2005. This series is noted for introducing new themes and styles yet unseen in other shows. The catchphrase for the series is \"To us, there are heroes.\" (ぼくたちには、ヒーローがいる Bokutachi ni wa, hīrō ga iru).",
                'img' => "kamen-rider/heisei/6.hibiki/1.6-hibiki-riders-1.jpg",
                'first_aired' => '2005-01-30',
                'last_aired' => '2006-01-22',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Kabuto",
                'slug' => Str::slug("Kabuto", '-'),
                'description' => "Kamen Rider Kabuto (仮面ライダーカブト Kamen Raidā Kabuto, Masked Rider Kabuto) is a Japanese tokusatsu superhero television series. It is the sixteenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. The series was broadcast on TV Asahi. The first episode aired on January 29, 2006, and with the final episode airing on January 21, 2007, completing the series with 49 episodes. It aired alongside GoGo-sentai-BoukengerIcon-crosswiki.png for Super Hero Time 2006. The series represents the 35th anniversary of the Masked Rider Series, as indicated by a notice at the beginning of the pilot episode reading, in Japanese, \"Kamen Rider 35th Anniversary Production.\" Kamen Rider Kabuto is the first Kamen Rider Series to be broadcast in high-definition format.",
                'img' => "kamen-rider/heisei/7.kabuto/1.7-kabuto-riders-2.jpg",
                'first_aired' => '2006-01-29',
                'last_aired' => '2007-01-21',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Den-O",
                'slug' => Str::slug("Den-O", '-'),
                'description' => "Kamen Rider Den-O (仮面ライダー電王［デンオウ］ Kamen Raidā Den'ō, Masked Rider Den-O) is the seventeenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. It premiered January 28, 2007 on TV Asahi, and concluded airing on January 20, 2008. It aired alongside Juken-sentai-GekirangerIcon-crosswiki.png for Super Hero Time 2007. Its lead actor Takeru Satoh is the first Kamen Rider Series lead born in the Heisei period of Japanese history.",
                'img' => "kamen-rider/heisei/8.den-o/1.8-den-o-riders-2.jpg",
                'first_aired' => '2007-01-28',
                'last_aired' => '2008-01-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Kiva",
                'slug' => Str::slug("Kiva", '-'),
                'description' => "Kamen Rider Kiva (仮面ライダーキバ Kamen Raidā Kiba, Masked Rider Kiva) is the title of the 2008 Kamen Rider Japanese tokusatsu television series produced by Toei Company and Ishimori Productions. It premiered on January 27, 2008, following the finale of Kamen Rider Den-O. It aired as a part of TV Asahi's 2008 Super Hero Time block with Engine-sentai-Go-OngerIcon-crosswiki.png. Advertisements showed a horror film theme to the series, with the motif for Kamen Rider Kiva as a vampire. The advertising slogan for the series is \"Wake up! Break the chains of destiny!!\" (覚醒（ウェイクアップ）! 運命（さだめ）の鎖を解き放て!! Weiku appu! Sadame no kusari o tokihanate!!). The first episode began with a commemoration of the series in honor of the seventieth anniversary of Shotaro Ishinomori's birthday.",
                'img' => "kamen-rider/heisei/9.kiva/1.9-kiva-riders-1.jpg",
                'first_aired' => '2008-01-27',
                'last_aired' => '2009-01-18',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Decade",
                'slug' => Str::slug("Decade", '-'),
                'description' => "Kamen Rider Decade (仮面ライダーディケイド Kamen Raidā Dikeido, Masked Rider DCD, Masked Rider Decade) is a Japanese tokusatsu drama and the 19th entry of the Kamen Rider Series. The series is the 10th entry of the Heisei Era and commemorates all of the Rider series to date. It premiered on January 25, 2009 alongside Samurai-sentai-ShinkengerIcon-crosswiki.png on TV Asahi's Super Hero Time block. After Kamen Rider Decade concluded early on August 30, 2009, Shinkenger was joined by Kamen Rider W.",
                'img' => "kamen-rider/heisei/10.decade/1.10-decade-riders-1.jpg",
                'first_aired' => '2009-01-25',
                'last_aired' => '2009-08-30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "W",
                'slug' => Str::slug("W", '-'),
                'description' => "Kamen Rider Double (仮面ライダーＷ［ダブル］ Kamen Raidā Daburu) is the main and eponymous protagonist of Kamen Rider W, a Kamen Rider who transforms from two people, Shotaro Hidari and Philip.",
                'img' => "kamen-rider/heisei/11.w/2.1-w-riders-1.jpg",
                'first_aired' => '2009-09-06',
                'last_aired' => '2010-08-29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "OOO",
                'slug' => Str::slug("OOO", '-'),
                'description' => "Kamen Rider OOO (仮面ライダーＯＯＯ［オーズ］ Kamen Raidā Ōzu) is a 2010-2011 Japanese tokusatsu drama in Toei Company's Kamen Rider Series, being the twelfth series in the Heisei period run and the twenty-first overall. It began airing on September 5, 2010, the week following the conclusion of Kamen Rider W,[1] joining Tensou-sentai-GoseigerIcon-crosswiki.png and then Kaizoku-sentai-GokaigerIcon-crosswiki.png in the Super Hero Time lineup, until its conclusion on August 28, 2011. The series' titular Kamen Rider made a cameo appearance in the film Kamen Rider W Forever: A to Z/The Gaia Memories of Fate. The catchphrase for the series is \"I'll transform!!!\" (俺が変身する!!! Ore ga henshin suru!!!).",
                'img' => "kamen-rider/heisei/12.ooo/2.2-ooo-riders-1.jpg",
                'first_aired' => '2010-09-05',
                'last_aired' => '2011-08-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Fourze",
                'slug' => Str::slug("Fourze", '-'),
                'description' => "Kamen Rider Fourze (仮面ライダーフォーゼ Kamen Raidā Fōze) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, being the thirteenth series in the Heisei period run and the twenty-second overall. It began airing on September 4, 2011, the week following the conclusion of Kamen Rider OOO, joining Kaizoku-sentai-GokaigerIcon-crosswiki.png, later Tokumei-sentai-Go-BustersIcon-crosswiki.png, in the Super Hero Time lineup. Trademarks on the title were filed by Toei in April 2011. The series commemorates not only the Kamen Rider Series' 40th anniversary but also the 50th anniversary of spaceflight, which began with Yuri Gagarin's Vostok 1 flight in 1961. The show's catchphrase is \"Switch on youth 'cause space is here!\" (青春スイッチオンで宇宙キター！ Seishun suitchi on de uchū kitā!), referencing the Fourze Driver transformation belt which gets its various powers from devices called Astroswitches to conjure attachments to Fourze's limbs. As with the two previous series, the protagonist of Fourze made his debut in the annual summer film of the show's direct predecessor, appearing in Kamen Rider OOO Wonderful: The Shogun and the 21 Core Medals.",
                'img' => "kamen-rider/heisei/13.fourze/2.3-fourze-riders-1.jpg",
                'first_aired' => '2011-09-04',
                'last_aired' => '2012-08-26',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Wizard",
                'slug' => Str::slug("Wizard", '-'),
                'description' => "Kamen Rider Wizard (仮面ライダーウィザード Kamen Raidā Uizādo) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, being the fourteenth series in the Heisei period run and the twenty-third overall. Trademarks on the title were filed by Toei in June 21, 2012. It began airing on September 2, 2012, joining Tokumei-sentai-Go-BustersIcon-crosswiki.png and then Zyuden-sentai-KyoryugerIcon-crosswiki.png in the Super Hero Time line-up following the finale of Kamen Rider Fourze. With Wizard finished, Kamen Rider Gaim joined Kyoryuger as part of Super Hero Time. Tsuyoshi Kida is the series' main screenwriter.",
                'img' => "kamen-rider/heisei/14.wizard/2.4-wizard-riders-2.jpg",
                'first_aired' => '2012-09-02',
                'last_aired' => '2013-08-29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Gaim",
                'slug' => Str::slug("Gaim", '-'),
                'description' => "Kamen Rider Gaim (仮面ライダー鎧武［ガイム］ Kamen Raidā Gaimu) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, it is the fifteenth series in the Heisei period run and the twenty-fourth series overall. Toei registered the copyright and trademark of the series, which started on October 6, 2013, joining Zyuden-sentai-KyoryugerIcon-crosswiki.png in the Super Hero Time line-up three weeks after the finale of Kamen Rider Wizard. After Kyoryuger concluded on February 9, 2014, Kamen Rider Gaim was joined in the Super Hero Time lineup with Ressha-sentai-ToQgerIcon-crosswiki.png. After the finale of Kamen Rider Gaim, Kamen Rider Drive joined ToQger on the Super Hero Time block. The catchphrase for the series are \"It's a Rider Warring (Sengoku) era.\" (ライダー戦国時代。 Raidā Sengoku Jidai) and \"How would you use your power?\" (キミはこの力どう使う? Kimi wa kono chikara dō tsukau).",
                'img' => "kamen-rider/heisei/15.gaim/2.5-gaim-riders-1.jpg",
                'first_aired' => '2013-10-06',
                'last_aired' => '2014-09-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Drive",
                'slug' => Str::slug("Drive", '-'),
                'description' => "Kamen Rider Drive (仮面ライダードライブ Kamen Raidā Doraibu) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the sixteenth series in the Heisei period run and the twenty-fifth series overall. The series started on October 5, 2014, joining Ressha-sentai-ToQgerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Gaim. Starting on February 22, 2015, Kamen Rider Drive was joined by Shuriken-sentai-NinningerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Drive, Kamen Rider Ghost joined Ninninger in the Super Hero Time line-up. Its series tagline is \"Start Your Engine!\"",
                'img' => "kamen-rider/heisei/16.drive/2.6-drive-riders-2.jpg",
                'first_aired' => '2014-10-05',
                'last_aired' => '2015-09-27',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Ghost",
                'slug' => Str::slug("Ghost", '-'),
                'description' => "Kamen Rider Ghost (仮面ライダーゴースト Kamen Raidā Gōsuto) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the seventeenth series in the Heisei period run and the twenty-sixth series overall. The series started on October 4, 2015, joining Shuriken-sentai-NinningerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Drive. After Ninninger concluded on February 7, 2016, the series was joined by Doubutsu-sentai-ZyuohgerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Ghost, Kamen Rider Ex-Aid joined Zyuohger in the Super Hero Time line-up.",
                'img' => "kamen-rider/heisei/17.ghost/2.7-ghost-riders-2.jpg",
                'first_aired' => '2015-10-04',
                'last_aired' => '2016-09-25',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Ex-Aid",
                'slug' => Str::slug("Ex-Aid", '-'),
                'description' => "Kamen Rider Ex-Aid (仮面ライダーエグゼイド Kamen Raidā Eguzeido) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the eighteenth series in the Heisei period run and the twenty-seventh series overall. The series started on October 2, 2016, joining Doubutsu-sentai-ZyuohgerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Ghost. Starting on February 12, 2017, the series was joined by Uchu-sentai-KyurangerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Ex-Aid, Kamen Rider Build joined Kyuranger in the Super Hero Time line-up. In 2019, this became the first Kamen Rider to air in Indonesia on RTV since Kamen Rider OOO on Indosiar in 2014. This show currently airs on the North American Japanese-language channel TV Japan.",
                'img' => "kamen-rider/heisei/18.ex-aid/2.8-ex-aid-riders-3.jpg",
                'first_aired' => '2016-10-02',
                'last_aired' => '2017-08-27',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Build",
                'slug' => Str::slug("Build", '-'),
                'description' => "Kamen Rider Build (仮面ライダービルド Kamen Raidā Birudo) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the nineteenth and penultimate series for a full Heisei period run and the twenty-eighth series overall. The series started on September 3, 2017, joining Uchu-sentai-KyurangerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Ex-Aid. After Kyuranger concluded on February 4, 2018, the series was joined by Kaitou-sentai-Lupinranger VS Keisatsu-sentai-PatrangerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Build, Kamen Rider Zi-O joined Lupinranger VS Patranger on the Super Hero Time block.",
                'img' => "kamen-rider/heisei/19.build/2.9-build-riders-1.jpg",
                'first_aired' => '2017-09-03',
                'last_aired' => '2018-08-26',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Zi-O",
                'slug' => Str::slug("Zi-O", '-'),
                'description' => "Kamen Rider Zi-O (仮面ライダージオウ Kamen Raidā Jiō) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the twentieth and final series in the Heisei period run, the first series to be produced around the Reiwa period, and the twenty-ninth series overall. The series started on September 2, 2018, joining Kaitou-sentai-Lupinranger VS Keisatsu-sentai-PatrangerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Build. After Lupinranger VS Patranger’s conclusion, it was joined by 4 Week Continuous Special Super-sentai-Strongest Battle!!Icon-crosswiki.png in February 2019 and later Kishiryu-sentai-RyusoulgerIcon-crosswiki.png in March 2019. After the finale of Kamen Rider Zi-O, Ryusoulger would air alongside Kamen Rider Zero-One in the Super Hero Time block.",
                'img' => "kamen-rider/heisei/20.zi-o/2.10-zi-o-riders-2.jpg",
                'first_aired' => '2018-09-02',
                'last_aired' => '2019-08-25',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Zero-One',
                'slug' => Str::slug('Zero-One', '-'),
                'description' => 'Kamen Rider Zero-One (仮面ライダーゼロワン, Kamen Raidā Zerowan) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the first series to debut during the Reiwa period and the thirty-fourth overall. The series premiered on September 1, 2019 and joined Kishiryu-sentai-Ryusoulger in the Super Hero Time line-up after the finale of Kamen Rider Zi-O. After Ryusoulger concluded, the series was joined by Mashin-sentai-Kiramager on March 8, 2020. After the finale of Zero-One, Kiramager was joined by Kamen Rider Saber in the Super Hero Time block.',
                'img' => "kamen-rider/reiwa/1.zero-one/zero-one-1.jpg",
                'first_aired' => '2019-09-01',
                'last_aired' => '2020-08-30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Saber',
                'slug' => Str::slug('Saber', '-'),
                'description' => 'Kamen Rider Saber (仮面ライダーセイバー聖刃, Kamen Raidā Seibā) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the second series to debut during the Reiwa period and the thirty-fifth overall. The series premiered on September 6, 2020 and joined Mashin-sentai-Kiramager in the Super Hero Time line-up after the finale of Kamen Rider Zero-One. After the conclusion of Kiramager, the series was joined by Kikai-sentai-Zenkaiger on March 7, 2021. After the finale of Saber, Zenkaiger was joined by Kamen Rider Revice in the Super Hero Time block.',
                'img' => "kamen-rider/reiwa/2.saber/saber-1.jpg",
                'first_aired' => '2020-09-06',
                'last_aired' => '2021-08-29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Revice',
                'slug' => Str::slug('Revice', '-'),
                'description' => 'Kamen Rider Revice (仮面ライダーリバイス, Kamen Raidā Ribaisu) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the third series to debut in the Reiwa Era and the thirty-sixth overall, and serves to commemorate the 50th Anniversary of the franchise. The series premiered on September 5, 2021, joining Kikai-sentai-Zenkaiger in the Super Hero Time line-up after the finale of Kamen Rider Saber. After Zenkaiger concluded on February 27, 2022, Revice was joined in the Super Hero Time line-up by Avataro-sentai-Donbrothers. After the finale of Revice, Donbrothers was joined by Kamen Rider Geats in the Super Hero Time Block.',
                'img' => "kamen-rider/reiwa/3.revice/revice-1.jpg",
                'first_aired' => '2021-09-05',
                'last_aired' => '2022-08-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Geats',
                'slug' => Str::slug('Geats', '-'),
                'description' => 'Kamen Rider Geats (仮面ライダーギーツ, Kamen Raidā Gītsu) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the fourth series to debut in the Reiwa Era and the thirty-seventh overall. The series premiered on September 4, 2022, joining Avataro-sentai-Donbrothers in the Super Hero Time lineup after the finale of Kamen Rider Revice. After Donbrothers concluded, Geats was joined in the Super Hero Time line-up by Ohsama-sentai-King-Ohger. After the finale of Geats, King-Ohger was joined by Kamen Rider Gotchard in the Super Hero Time block.',
                'img' => "kamen-rider/reiwa/4.geats/geats-1.jpg",
                'first_aired' => '2022-09-04',
                'last_aired' => '2023-08-27',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Gotchard',
                'slug' => Str::slug('Gotchard', '-'),
                'description' => 'Kamen Rider Gotchard (仮面ライダーガッチャード, Kamen Raidā Gatchādo) is a Japanese tokusatsu drama in Toei Company\'s Kamen Rider Series. It is the fifth series to debut in the Reiwa Era and the thirty-eighth overall. The series premiered on September 3, 2023, joining Ohsama-sentai-King-Ohger in the Super Hero Time lineup after the finale of Kamen Rider Geats. After King-Ohger concluded, Gotchard was joined in the Super Hero Time line-up by Bakuage-sentai-Boonboomger on March 3, 2024. After the finale of Gotchard, Boonboomger was joined in the line-up by Kamen Rider Gavv in the Super Hero Time block.',
                'img' => "kamen-rider/reiwa/5.gotchard/gotchard-1.jpg",
                'first_aired' => '2023-09-03',
                'last_aired' => '2024-08-25',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Gorenger',
                'slug' => Str::slug('Gorenger', '-'),
                'description' => 'The Super-sentai-Series (スーパー戦隊シリーズ Sūpā-sentai-Shirīzu) is the name given to the long-running Japanese "superhero team" genre of shows produced by Toei and Bandai and aired by TV Asahi (formerly known as NET), that is used as the basis for Power-rangers. ("Super" refers to their use of mecha, and "Sentai" is the Japanese word for "task force" or, literally, "fighting squadron" and was also a term used for Japanese squadrons in World War II.)',
                'img' => "super-sentai/showa/1-himitsu-sentai-goranger-five-rangers-1.jpg",
                'first_aired' => '1975-04-05',
                'last_aired' => '1977-03-26',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'J.A.K.Q.',
                'slug' => Str::slug('J.A.K.Q.', '-'),
                'description' => null,
                'img' => "super-sentai/showa/2-j.a.k.q-dengekitai-jakq-1.jpg",
                'first_aired' => '1977-04-09',
                'last_aired' => '1977-12-24',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Fever J',
                'slug' => Str::slug('Fever J', '-'),
                'description' => null,
                'img' => "super-sentai/showa/3-battle-fever-j-1.jpg",
                'first_aired' => '1979-02-03',
                'last_aired' => '1980-01-26',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Denziman',
                'slug' => Str::slug('Denziman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/4-denshi-sentai-denjiman-1.jpg",
                'first_aired' => '1980-02-02',
                'last_aired' => '1981-01-31',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Sun Vulcan',
                'slug' => Str::slug('Sun Vulcan', '-'),
                'description' => null,
                'img' => "super-sentai/showa/5-taiyo-sentai-sun-vulcan-1.jpg",
                'first_aired' => '1981-02-07',
                'last_aired' => '1982-01-30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Goggle V',
                'slug' => Str::slug('Goggle V', '-'),
                'description' => null,
                'img' => "super-sentai/showa/6-dai-sentai-goggle-five-1.jpg",
                'first_aired' => '1982-02-06',
                'last_aired' => '1983-01-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Dynaman',
                'slug' => Str::slug('Dynaman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/7-kagaku-sentai-dynaman-1.jpg",
                'first_aired' => '1983-02-05',
                'last_aired' => '1984-01-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Bioman',
                'slug' => Str::slug('Bioman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/8-choudenshi-bioman-1.jpg",
                'first_aired' => '1984-02-04',
                'last_aired' => '1985-01-26',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Changeman',
                'slug' => Str::slug('Changeman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/9-dengeki-sentai-changeman-1.jpg",
                'first_aired' => '1985-02-02',
                'last_aired' => '1986-02-22',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Flashman',
                'slug' => Str::slug('Flashman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/10-choushinsei-flashman-1.jpg",
                'first_aired' => '1986-03-01',
                'last_aired' => '1987-02-21',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Maskman',
                'slug' => Str::slug('Maskman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/11-hikari-sentai-maskman-1.jpg",
                'first_aired' => '1987-02-28',
                'last_aired' => '1988-02-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Liveman',
                'slug' => Str::slug('Liveman', '-'),
                'description' => null,
                'img' => "super-sentai/showa/12-choujuu-sentai-liveman-1.jpg",
                'first_aired' => '1988-02-27',
                'last_aired' => '1989-02-18',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Turboranger',
                'slug' => Str::slug('Turboranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/13-kousoku-sentai-turboranger-1.jpg",
                'first_aired' => '1989-03-04',
                'last_aired' => '1990-02-23',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Fiveman',
                'slug' => Str::slug('Fiveman', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/14-chikyuu-sentai-fiveman-1.jpg",
                'first_aired' => '1990-03-02',
                'last_aired' => '1991-02-08',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Jetman',
                'slug' => Str::slug('Jetman', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/15-choujin-sentai-jetman-1.jpg",
                'first_aired' => '1991-02-15',
                'last_aired' => '1992-02-14',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Zyuranger',
                'slug' => Str::slug('Zyuranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/16-kyouryuu-sentai-zyuranger-jpn-mighty-morphin-power-rangers-usa-1.jpg",
                'first_aired' => '1992-02-21',
                'last_aired' => '1993-02-12',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Dairanger',
                'slug' => Str::slug('Dairanger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/17-gosei-sentai-dairanger-jpn-mighty-morphin-power-rangers-2-usa-star-ranger-ina-1.jpg",
                'first_aired' => '1993-02-19',
                'last_aired' => '1994-02-11',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Kakuranger',
                'slug' => Str::slug('Kakuranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/18-ninja-sentai-kakuranger-jpn-mighty-morphin-power-alien-rangers-3-usa-ninja-ranger-ina-1.jpg",
                'first_aired' => '1994-02-18',
                'last_aired' => '1995-02-24',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Ohranger',
                'slug' => Str::slug('Ohranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/19-choriki-sentai-ohranger-jpn-power-rangers-zeo-usa-oh-ranger-ina-1.jpg",
                'first_aired' => '1995-03-03',
                'last_aired' => '1996-02-23',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Carranger',
                'slug' => Str::slug('Carranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/20-gekisou-sentai-carranger-jpn-power-rangers-turbo-usa-1.jpg",
                'first_aired' => '1996-03-01',
                'last_aired' => '1997-02-07',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Megaranger',
                'slug' => Str::slug('Megaranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/21-denji-sentai-megaranger-jpn-power-rangers-in-space-usa-1.jpg",
                'first_aired' => '1997-02-14',
                'last_aired' => '1998-02-15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gingaman',
                'slug' => Str::slug('Gingaman', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/22-seijuu-sentai-gingaman-jpn-power-rangers-lost-galaxy-usa-6.jpg",
                'first_aired' => '1998-02-22',
                'last_aired' => '1999-02-14',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Go Go V',
                'slug' => Str::slug('Go Go V', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/23-kyukyu-sentai-gogo-v-jpn-power-rangers-lightspeed-rescue-usa-1.jpg",
                'first_aired' => '1999-02-21',
                'last_aired' => '2000-02-06',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Timeranger',
                'slug' => Str::slug('Timeranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/24-mirai-sentai-timeranger-jpn-power-rangers-time-force-usa-1.jpg",
                'first_aired' => '2000-02-13',
                'last_aired' => '2001-02-04',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gaoranger',
                'slug' => Str::slug('Gaoranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/25-hyaku-juu-sentai-gaoranger-jpn-power-rangers-wild-force-usa-1.jpg",
                'first_aired' => '2001-02-18',
                'last_aired' => '2002-02-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Hurricaneger',
                'slug' => Str::slug('Hurricaneger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/26-ninpuu-sentai-hurricanger-jpn-power-rangers-ninja-storm-usa-1.jpg",
                'first_aired' => '2002-02-17',
                'last_aired' => '2003-02-09',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Abaranger',
                'slug' => Str::slug('Abaranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/27-bakuryuu-sentai-abaranger-jpn-power-rangers-dino-thunder-usa-1.jpg",
                'first_aired' => '2003-02-16',
                'last_aired' => '2004-02-08',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Dekaranger',
                'slug' => Str::slug('Dekaranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/28-tokusou-sentai-dekaranger-jpn-power-rangers-s.p.d-usa-1.jpg",
                'first_aired' => '2004-02-15',
                'last_aired' => '2005-02-06',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Magiranger',
                'slug' => Str::slug('Magiranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/29-mahou-sentai-magiranger-jpn-power-rangers-mystic-force-usa-1.jpg",
                'first_aired' => '2005-02-13',
                'last_aired' => '2006-02-12',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Boukenger',
                'slug' => Str::slug('Boukenger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/30-gougou-sentai-boukenger-jpn-power-rangers-operation-overdrive-usa-1.jpg",
                'first_aired' => '2006-02-19',
                'last_aired' => '2007-02-11',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gekiranger',
                'slug' => Str::slug('Gekiranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/31-juken-sentai-gekiranger-jpn-power-rangers-jungle-fury-usa-1.jpg",
                'first_aired' => '2007-02-18',
                'last_aired' => '2008-02-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Go-Onger',
                'slug' => Str::slug('Go-Onger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/32-engine-sentai-go-onger-jpn-power-rangers-rpm-usa-1.jpg",
                'first_aired' => '2008-02-17',
                'last_aired' => '2009-02-08',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Shinkenger',
                'slug' => Str::slug('Shinkenger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/33-samurai-sentai-shinkenger-jpn-power-rangers-samurai-usa-1.jpg",
                'first_aired' => '2009-02-15',
                'last_aired' => '2010-02-07',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Goseiger',
                'slug' => Str::slug('Goseiger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/34-tensou-sentai-goseiger-jpn-power-rangers-megaforce-usa-1.jpg",
                'first_aired' => '2010-02-14',
                'last_aired' => '2011-02-06',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gokaiger',
                'slug' => Str::slug('Gokaiger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/35-kaizoku-sentai-gokaiger-jpn-power-rangers-super-megaforce-usa-1.jpg",
                'first_aired' => '2011-02-13',
                'last_aired' => '2012-02-19',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Go-Busters',
                'slug' => Str::slug('Go-Busters', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/36-tokumei-sentai-go-busters-1.jpg",
                'first_aired' => '2012-02-26',
                'last_aired' => '2013-02-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Kyoryuger',
                'slug' => Str::slug('Kyoryuger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/37-zyuden-sentai-kyoryuger-1.jpg",
                'first_aired' => '2013-02-17',
                'last_aired' => '2014-02-09',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'ToQger',
                'slug' => Str::slug('ToQger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/38-ressha-sentai-tokkyuger-1.jpg",
                'first_aired' => '2014-02-16',
                'last_aired' => '2015-02-15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Ninninger',
                'slug' => Str::slug('Ninninger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/39-shuriken-sentai-ninninger-1.jpg",
                'first_aired' => '2015-02-22',
                'last_aired' => '2016-02-07',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Zyuohger',
                'slug' => Str::slug('Zyuohger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/40-doubutsu-sentai-zyouhger-1.jpg",
                'first_aired' => '2016-02-14',
                'last_aired' => '2017-02-05',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Kyuuranger',
                'slug' => Str::slug('Kyuuranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/41-uchuu-sentai-kyuuranger-1.jpg",
                'first_aired' => '2017-02-12',
                'last_aired' => '2018-02-04',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Lupinranger VS Patranger',
                'slug' => Str::slug('Lupinranger VS Patranger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/42-kaitou-sentai-lupinranger-keisatsu-sentai-patranger-lupat-rangers-1.jpg",
                'first_aired' => '2018-02-11',
                'last_aired' => '2019-02-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Ryusoulger',
                'slug' => Str::slug('Ryusoulger', '-'),
                'description' => null,
                'img' => "super-sentai/heisei/43-kishiryu-sentai-ryusoulger-1.jpg",
                'first_aired' => '2019-03-17',
                'last_aired' => '2020-03-01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Kiramager',
                'slug' => Str::slug('Kiramager', '-'),
                'description' => null,
                'img' => "super-sentai/reiwa/1-mashin-sentai-kiramager/mashin-sentai-kiramager-1.jpg",
                'first_aired' => '2020-03-08',
                'last_aired' => '2021-02-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Zenkaiger',
                'slug' => Str::slug('Zenkaiger', '-'),
                'description' => null,
                'img' => "super-sentai/reiwa/2-kikai-sentai-zenkaiger/kikai-sentai-zenkaiger-1.jpg",
                'first_aired' => '2021-03-07',
                'last_aired' => '2022-02-27',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Donbrothers',
                'slug' => Str::slug('Donbrothers', '-'),
                'description' => null,
                'img' => "super-sentai/reiwa/3-avataro-sentai-donbrothers/avataro-sentai-donbrothers-1.jpg",
                'first_aired' => '2022-03-06',
                'last_aired' => '2023-02-26',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'King-Ohger',
                'slug' => Str::slug('King-Ohger', '-'),
                'description' => null,
                'img' => "super-sentai/reiwa/4-ohsama-sentai-king-ohger/ohsama-sentai-king-ohger-1.jpg",
                'first_aired' => '2023-03-05',
                'last_aired' => '2024-02-25',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Boonboomger',
                'slug' => Str::slug('Boonboomger', '-'),
                'description' => null,
                'img' => "logo.png",
                'first_aired' => '2024-03-03',
                'last_aired' => '2025-02-09',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Ultraman',
                'slug' => Str::slug('Ultraman', '-'),
                'description' => 'Ultraman (ウルトラマン, Urutoraman) is an alien from a place called the Land of Light in Nebula M78, who chased the monster Bemular to Planet Earth, and merged with Shin Hayata during his tenure there. He is the first Ultra to visit Earth and defended the planet against Kaiju until he was recalled after his battle with Zetton. Ultraman was given his title by his human host.',
                'img' => "ultraman/showa/1.ultraman/ultraman-1.jpg",
                'first_aired' => '1966-07-17',
                'last_aired' => '1967-04-09',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Ultra Seven',
                'slug' => Str::slug('Ultra Seven', '-'),
                'description' => null,
                'img' => "ultraman/showa/2.ultra-seven/ultra-seven-1.jpg",
                'first_aired' => '1967-10-01',
                'last_aired' => '1968-09-08',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Jack',
                'slug' => Str::slug('Jack', '-'),
                'description' => null,
                'img' => "ultraman/showa/3.ultraman-jack/ultraman-jack-1.jpg",
                'first_aired' => '1971-04-02',
                'last_aired' => '1972-03-31',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Ace',
                'slug' => Str::slug('Ace', '-'),
                'description' => null,
                'img' => "ultraman/showa/4.ultraman-ace/ultraman-ace-1.jpg",
                'first_aired' => '1972-04-07',
                'last_aired' => '1973-03-30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Taro',
                'slug' => Str::slug('Taro', '-'),
                'description' => null,
                'img' => "ultraman/showa/5.ultraman-taro/ultraman-taro-2.jpg",
                'first_aired' => '1973-04-06',
                'last_aired' => '1974-04-05',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Leo',
                'slug' => Str::slug('Leo', '-'),
                'description' => null,
                'img' => "ultraman/showa/6.ultraman-leo/ultraman-leo-2.jpg",
                'first_aired' => '1974-04-12',
                'last_aired' => '1975-03-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => '80',
                'slug' => Str::slug('80', '-'),
                'description' => null,
                'img' => "ultraman/showa/7.ultraman-80/ultraman-80-1.jpg",
                'first_aired' => '1980-04-02',
                'last_aired' => '1981-03-25',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Zoffy',
                'slug' => Str::slug('Zoffy', '-'),
                'description' => null,
                'img' => "ultraman/showa/8.ultraman-zoffy/ultraman-zoffy-1.jpg",
                'first_aired' => '1984-03-17',
                'last_aired' => '1984-03-17',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Tiga',
                'slug' => Str::slug('Tiga', '-'),
                'description' => null,
                'img' => "ultraman/heisei/1.ultraman-tiga/ultraman-tiga-1.jpg",
                'first_aired' => '1996-09-07',
                'last_aired' => '1997-08-30',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Dyna',
                'slug' => Str::slug('Dyna', '-'),
                'description' => null,
                'img' => "ultraman/heisei/2.ultraman-dyna/ultraman-dyna-1.jpg",
                'first_aired' => '1997-09-06',
                'last_aired' => '1998-08-29',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Gaia',
                'slug' => Str::slug('Gaia', '-'),
                'description' => null,
                'img' => "ultraman/heisei/3.ultraman-gaia/ultraman-gaia-1.jpg",
                'first_aired' => '1998-09-05',
                'last_aired' => '1999-08-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Cosmos',
                'slug' => Str::slug('Cosmos', '-'),
                'description' => null,
                'img' => "ultraman/heisei/4.ultraman-cosmos/ultraman-cosmos-1.jpg",
                'first_aired' => '2001-07-07',
                'last_aired' => '2002-09-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Nexus',
                'slug' => Str::slug('Nexus', '-'),
                'description' => null,
                'img' => "ultraman/heisei/5.ultraman-nexus/ultraman-nexus-3.jpg",
                'first_aired' => '2004-10-02',
                'last_aired' => '2005-06-25',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Max',
                'slug' => Str::slug('Max', '-'),
                'description' => null,
                'img' => "ultraman/heisei/6.ultraman-max/ultraman-max-1.jpg",
                'first_aired' => '2005-07-02',
                'last_aired' => '2006-03-01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Mebius',
                'slug' => Str::slug('Mebius', '-'),
                'description' => null,
                'img' => "ultraman/heisei/7.ultraman-mebius/ultraman-mebius-1.jpg",
                'first_aired' => '2006-04-08',
                'last_aired' => '2007-03-31',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Zero',
                'slug' => Str::slug('Zero', '-'),
                'description' => null,
                'img' => "ultraman/heisei/8.ultraman-zero/ultraman-zero-3.jpg",
                'first_aired' => '2010-12-23',
                'last_aired' => '2010-12-23',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Ginga',
                'slug' => Str::slug('Ginga', '-'),
                'description' => null,
                'img' => "ultraman/heisei/9.ultraman-ginga/ultraman-ginga-1.jpg",
                'first_aired' => '2013-07-10',
                'last_aired' => '2013-12-18',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Ginga S',
                'slug' => Str::slug('Ginga S', '-'),
                'description' => null,
                'img' => "ultraman/heisei/10.ultraman-ginga-s/ultraman-ginga-s-1.jpg",
                'first_aired' => '2014-07-15',
                'last_aired' => '2014-12-23',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'X',
                'slug' => Str::slug('X', '-'),
                'description' => null,
                'img' => "ultraman/heisei/11.ultraman-x/ultraman-x-1.jpg",
                'first_aired' => '2015-07-14',
                'last_aired' => '2016-01-05',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Orb',
                'slug' => Str::slug('Orb', '-'),
                'description' => null,
                'img' => "ultraman/heisei/12.ultraman-orb/ultraman-orb-1.jpg",
                'first_aired' => '2016-07-09',
                'last_aired' => '2016-12-24',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Geed',
                'slug' => Str::slug('Geed', '-'),
                'description' => null,
                'img' => "ultraman/heisei/13.ultraman-geed/ultraman-geed-1.jpg",
                'first_aired' => '2017-07-08',
                'last_aired' => '2017-12-23',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'R/B',
                'slug' => Str::slug('R/B', '-'),
                'description' => null,
                'img' => "ultraman/heisei/14.ultraman-rb/ultraman-rb-1.jpg",
                'first_aired' => '2018-07-07',
                'last_aired' => '2018-12-22',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Taiga',
                'slug' => Str::slug('Taiga', '-'),
                'description' => null,
                'img' => "ultraman/reiwa/1.ultraman-taiga/ultraman-taiga-1.jpg",
                'first_aired' => '2019-07-06',
                'last_aired' => '2019-12-28',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Z',
                'slug' => Str::slug('Z', '-'),
                'description' => null,
                'img' => "ultraman/reiwa/2.ultraman-z/ultraman-z-1.jpg",
                'first_aired' => '2020-06-20',
                'last_aired' => '2020-12-19',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Trigger',
                'slug' => Str::slug('Trigger', '-'),
                'description' => null,
                'img' => "ultraman/reiwa/3.ultraman-trigger/ultraman-trigger-1.jpg",
                'first_aired' => '2021-07-10',
                'last_aired' => '2022-01-22',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Decker',
                'slug' => Str::slug('Decker', '-'),
                'description' => null,
                'img' => "ultraman/reiwa/4.ultraman-decker/ultraman-decker-1.jpg",
                'first_aired' => '2022-07-09',
                'last_aired' => '2023-01-21',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Blazar',
                'slug' => Str::slug('Blazar', '-'),
                'description' => null,
                'img' => "logo.png",
                'first_aired' => '2023-07-08',
                'last_aired' => '2024-01-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ]);

        foreach ($data as $category) {
            Category::create($category);
        }
    }

    private function Era(string $name): string
    {
        $era = Era::where('name', $name)->first();
        if (!$era) {
            $era = Era::create([
                'name' => $name,
            ]);
        }
        return $era->id;
    }

    private function Franchise(string $name): string
    {
        $franchise = Franchise::where('name', $name)->first();
        if (!$franchise) {
            $franchise = Franchise::create([
                'name' => $name,
            ]);
        }
        return $franchise->id;
    }
}
