<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class VideoOtherSeeder extends Seeder
{
    public function run(): void
    {
        $timestamp = [
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ];

        $data = collect([
            // GARO
            ['title' => "Picture Book (絵本 Ehon)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 1, 'airdate' => '2005-10-07'],
            ['title' => "Inga (陰我 Inga)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 2, 'airdate' => '2005-10-14'],
            ['title' => "Clock (時計 Tokei)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 3, 'airdate' => '2005-10-21'],
            ['title' => "Dinner (晩餐 Bansan)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 4, 'airdate' => '2005-10-28'],
            ['title' => "Moonlight (月光 Gekkō)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 5, 'airdate' => '2005-11-04'],
            ['title' => "Beauty (美貌 Bibyō)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 6, 'airdate' => '2005-11-11'],
            ['title' => "Silver Fang (銀牙 Ginga)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 7, 'airdate' => '2005-11-18'],
            ['title' => "Ring (指輪 Yubiwa)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 8, 'airdate' => '2005-11-25'],
            ['title' => "Ordeal (試練 Shiren)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 9, 'airdate' => '2005-12-02'],
            ['title' => "Puppet (人形 Ningyō)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 10, 'airdate' => '2005-12-09'],
            ['title' => "Game (遊戯 Yūgi)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 11, 'airdate' => '2005-12-16'],
            ['title' => "Taiga (大河 Taiga)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 12, 'airdate' => '2005-12-23'],
            ['title' => "Promise (約束 Yakusoku)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 13, 'airdate' => '2006-01-06'],
            ['title' => "Nightmare (悪夢 Akumu)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 14, 'airdate' => '2006-01-13'],
            ['title' => "Statue (像 Zō)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 15, 'airdate' => '2006-01-20'],
            ['title' => "Red Sake (赤酒 Akazake)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 16, 'airdate' => '2006-01-27'],
            ['title' => "Aquarium (水槽 Suisō)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 17, 'airdate' => '2006-02-03'],
            ['title' => "World Charm (界符 Kaifu)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 18, 'airdate' => '2006-02-10'],
            ['title' => "Black Flame (黒炎 Kokuen)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 19, 'airdate' => '2006-02-17'],
            ['title' => "Life (生命 Inochi)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 20, 'airdate' => '2006-02-24'],
            ['title' => "Magic Bullet (魔弾 Madan)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 21, 'airdate' => '2006-03-03'],
            ['title' => "Engraving (刻印 Kokuin)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 22, 'airdate' => '2006-03-10'],
            ['title' => "Heart Destruction (心滅 Shinmetsu)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 23, 'airdate' => '2006-03-17'],
            ['title' => "Girl (少女 Shōjo)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 24, 'airdate' => '2006-03-24'],
            ['title' => "Heroic Spirits (英霊 Eirei)", 'category_id' => $this->Category('garo'), 'type' => 'episode', 'number' => 25, 'airdate' => '2006-03-31'],
            ['title' => "Spark (火花, Hibana)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 1, 'airdate' => '2011-10-06'],
            ['title' => "Street Light (街灯, Gaitō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 2, 'airdate' => '2011-10-13'],
            ['title' => "Wheels (車輪, Sharin)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 3, 'airdate' => '2011-10-20'],
            ['title' => "Trump Card / Joker (切札, Kirifuda)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 4, 'airdate' => '2011-10-27'],
            ['title' => "Hell / Naraka (奈落, Naraku)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 5, 'airdate' => '2011-11-03'],
            ['title' => "Letter (手紙, Tegami)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 6, 'airdate' => '2011-11-10'],
            ['title' => "Flash (閃光, Senkō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 7, 'airdate' => '2011-11-17'],
            ['title' => "Demon Sword (妖刀, Yōtō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 8, 'airdate' => '2011-11-24'],
            ['title' => "Makeup (化粧, Keshō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 9, 'airdate' => '2011-12-01'],
            ['title' => "Secret (秘密, Himitsu)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 10, 'airdate' => '2011-12-08'],
            ['title' => "Howl (咆哮, Hōkō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 11, 'airdate' => '2011-12-15'],
            ['title' => "Fruit (果実, Kajitsu)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 12, 'airdate' => '2011-12-22'],
            ['title' => "Wizard Water / Magic Water (仙水, Sen-sui)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 13, 'airdate' => '2012-01-05'],
            ['title' => "Reunion (再会, Saikai)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 14, 'airdate' => '2012-01-12'],
            ['title' => "Brothers (同胞, Dōhō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 15, 'airdate' => '2012-01-19'],
            ['title' => "Mask (仮面, Kamen)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 16, 'airdate' => '2012-01-26'],
            ['title' => "Red Brush (赤筆, Akafude)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 17, 'airdate' => '2012-02-02'],
            ['title' => "Beast Herd / Beast Pack (群獣, Gunjū)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 18, 'airdate' => '2012-02-09'],
            ['title' => "Paradise (楽園, Rakuen)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 19, 'airdate' => '2012-02-16'],
            ['title' => "Train (列車, Ressha)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 20, 'airdate' => '2012-02-23'],
            ['title' => "Stronghold / Fortress (牙城, Gajō)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 21, 'airdate' => '2012-03-01'],
            ['title' => "Sworn Friends / Alliance (盟友, Meiyū)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 22, 'airdate' => '2012-03-08'],
            ['title' => "Golden (金色, Kin’iro)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 23, 'airdate' => '2012-03-15'],
            ['title' => "Era / Time (時代, Jidai)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 24, 'airdate' => '2012-03-22'],
            ['title' => "My title is Garo - The History of Kouga Saejima's Battles (我が名は牙狼 - 冴島鋼牙 戦いの軌跡, Waga Na wa Garo)", 'category_id' => $this->Category('makai-senki'), 'type' => 'episode', 'number' => 25, 'airdate' => '2012-03-29'],
            ['title' => "Ryuga (流牙 Ryūga)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 1, 'airdate' => '2013-04-05'],
            ['title' => "Gold Wave (波 Nami)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 2, 'airdate' => '2013-04-12'],
            ['title' => "Dungeon (迷 Mayoi)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 3, 'airdate' => '2013-04-19'],
            ['title' => "Dream (夢 Yume)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 4, 'airdate' => '2013-04-26'],
            ['title' => "Nightmare (悪夢 Akumu)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 5, 'airdate' => '2013-05-03'],
            ['title' => "Rock (ロック Rokku)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 6, 'airdate' => '2013-05-10'],
            ['title' => "Dining (食卓 Shokutaku)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 7, 'airdate' => '2013-05-17'],
            ['title' => "Scoop (スクープ Sukūpu)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 8, 'airdate' => '2013-05-24'],
            ['title' => "Sonshi (尊士 Sonshi)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 9, 'airdate' => '2013-05-31'],
            ['title' => "Promise (約束 Yakusoku)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 10, 'airdate' => '2013-06-07'],
            ['title' => "Desire (虜 Toriko)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 11, 'airdate' => '2013-06-14'],
            ['title' => "Trap (罠 Wana)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 12, 'airdate' => '2013-06-21'],
            ['title' => "Hunting (狩り Kari)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 13, 'airdate' => '2013-06-28'],
            ['title' => "Hyena (ハイエナ Haiena)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 14, 'airdate' => '2013-07-05'],
            ['title' => "Hint (ヒント Hinto)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 15, 'airdate' => '2013-07-12'],
            ['title' => "Lost (迷失 Meishitsu)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 16, 'airdate' => '2013-07-19'],
            ['title' => "Tousei (礼 Rei)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 17, 'airdate' => '2013-07-26'],
            ['title' => "War (義 Gi)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 18, 'airdate' => '2013-08-02'],
            ['title' => "Hope (希望 Kibō)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 19, 'airdate' => '2013-08-09'],
            ['title' => "Mother (母 Haha)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 20, 'airdate' => '2013-08-16'],
            ['title' => "Justice (正義 Seigi)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 21, 'airdate' => '2013-08-23'],
            ['title' => "Master (盟友／主 Meiyū / Aruji)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 22, 'airdate' => '2013-08-30'],
            ['title' => "Gold (輝 Kagayaki)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 23, 'airdate' => '2013-09-06'],
            ['title' => "Future (未来 Mirai)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 24, 'airdate' => '2013-09-13'],
            ['title' => "Beginning (道 Michi)", 'category_id' => $this->Category('yami-o-terasu-mono'), 'type' => 'episode', 'number' => 25, 'airdate' => '2013-09-20'],
            ['title' => "Dolce (血のドルチェ Chi no Doruche)", 'category_id' => $this->Category('zero-black-blood'), 'type' => 'episode', 'number' => 1, 'airdate' => '2014-03-05'],
            ['title' => "Community (コミュニティ Komyuniti)", 'category_id' => $this->Category('zero-black-blood'), 'type' => 'episode', 'number' => 2, 'airdate' => '2014-03-05'],
            ['title' => "Enemy (外敵 Gaiteki)", 'category_id' => $this->Category('zero-black-blood'), 'type' => 'episode', 'number' => 3, 'airdate' => '2014-03-06'],
            ['title' => "Dream (真実の夢 Shinjitsu no Yume)", 'category_id' => $this->Category('zero-black-blood'), 'type' => 'episode', 'number' => 4, 'airdate' => '2014-03-06'],
            ['title' => "Decision (決意 Ketsui)", 'category_id' => $this->Category('zero-black-blood'), 'type' => 'episode', 'number' => 5, 'airdate' => '2014-03-07'],
            ['title' => "Savior (救世主 Kyūseishu)", 'category_id' => $this->Category('zero-black-blood'), 'type' => 'episode', 'number' => 6, 'airdate' => '2014-03-07'],
            ['title' => "Fossil (化石 Kaseki)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 1, 'airdate' => '2014-04-04'],
            ['title' => "Pests (害虫 Gaichū)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 2, 'airdate' => '2014-04-11'],
            ['title' => "Greenhouse (温室 Onshitsu)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 3, 'airdate' => '2014-04-18'],
            ['title' => "Movie (映画 Eiga)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 4, 'airdate' => '2014-04-25'],
            ['title' => "Star Chart (星図 Seizu)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 5, 'airdate' => '2014-05-02'],
            ['title' => "Wind Chimes (風鈴 Fūrin)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 6, 'airdate' => '2014-05-09'],
            ['title' => "Myth (神話 Shinwa)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 7, 'airdate' => '2014-05-16'],
            ['title' => "Family (家族 Kazoku)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 8, 'airdate' => '2014-05-23'],
            ['title' => "Raising (飼育 Shiiku)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 9, 'airdate' => '2014-05-30'],
            ['title' => "Dinner Table (食卓 Shokutaku)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 10, 'airdate' => '2014-06-06'],
            ['title' => "Manga (漫画 Manga)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 11, 'airdate' => '2014-06-13'],
            ['title' => "Word Spirit (言霊 Kotodama)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 12, 'airdate' => '2014-06-20'],
            ['title' => "Ferocious Beast (凶獣 Kyōjū)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 13, 'airdate' => '2014-06-27'],
            ['title' => "Transformation (変身 Henshin)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 14, 'airdate' => '2014-07-11'],
            ['title' => "Tea (紅茶 Kōcha)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 15, 'airdate' => '2014-07-18'],
            ['title' => "Scream (絶叫 Zekkyō)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 16, 'airdate' => '2014-07-25'],
            ['title' => "The Boy (少年 Shōnen)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 17, 'airdate' => '2014-08-01'],
            ['title' => "Crimson Lotus (紅蓮 Guren)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 18, 'airdate' => '2014-08-08'],
            ['title' => "Suite (組曲 Kumikyoku)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 19, 'airdate' => '2014-08-15'],
            ['title' => "Tetsujin (鉄人 Tetsujin)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 20, 'airdate' => '2014-08-22'],
            ['title' => "Afterimage (残像 Zanzō)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 21, 'airdate' => '2014-08-29'],
            ['title' => "Guard Dog (番犬 Banken)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 22, 'airdate' => '2014-09-05'],
            ['title' => "Reminiscence (追想 Tsuisō)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 23, 'airdate' => '2014-09-12'],
            ['title' => "Marebito (稀人 Marebito)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 24, 'airdate' => '2014-09-19'],
            ['title' => "Destiny (天命 Tenmei)", 'category_id' => $this->Category('makai-no-hana'), 'type' => 'episode', 'number' => 25, 'airdate' => '2014-09-26'],
            ['title' => "Sword (剣 Tsurugi)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 1, 'airdate' => '2015-04-10'],
            ['title' => "Flame (炎 Honō)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 2, 'airdate' => '2015-04-17'],
            ['title' => "Butterfly (蝶 Chō)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 3, 'airdate' => '2015-04-24'],
            ['title' => "Axe (斧 Ono)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 4, 'airdate' => '2015-05-01'],
            ['title' => "Sin (罪 Tsumi)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 5, 'airdate' => '2015-05-08'],
            ['title' => "Frame (額 Gaku)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 6, 'airdate' => '2015-05-15'],
            ['title' => "Spell (術 Jutsu)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 7, 'airdate' => '2015-05-22'],
            ['title' => "Brush (筆 Fude)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 8, 'airdate' => '2015-06-05'],
            ['title' => "Feathers (羽 Hane)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 9, 'airdate' => '2015-06-12'],
            ['title' => "Thunder (雷 Ikazuchi)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 10, 'airdate' => '2015-06-19'],
            ['title' => "Trap (罠 Wana)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 11, 'airdate' => '2015-06-26'],
            ['title' => "Bonds (絆 Kizuna)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 12, 'airdate' => '2015-07-03'],
            ['title' => "Swamp (沼 Numa)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 13, 'airdate' => '2015-07-10'],
            ['title' => "Signpost (標 Shirube)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 14, 'airdate' => '2015-07-17'],
            ['title' => "Fort (砦 Toride)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 15, 'airdate' => '2015-07-24'],
            ['title' => "War (戦 Ikusa)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 16, 'airdate' => '2015-07-31'],
            ['title' => "Mirror (鏡 Kagami)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 17, 'airdate' => '2015-08-07'],
            ['title' => "Darkness (闇 Yami)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 18, 'airdate' => '2015-08-14'],
            ['title' => "Heart (心 Kokoro)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 19, 'airdate' => '2015-08-21'],
            ['title' => "Fountain (泉 Izumi)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 20, 'airdate' => '2015-08-28'],
            ['title' => "King (王 Ō)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 21, 'airdate' => '2015-09-04'],
            ['title' => "Castle (城 Shiro)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 22, 'airdate' => '2015-09-11'],
            ['title' => "Storm (嵐 Arashi)", 'category_id' => $this->Category('gold-storm-sho'), 'type' => 'episode', 'number' => 23, 'airdate' => '2015-09-18'],
            ['title' => "Requiem (鎮魂歌 Chinkonka)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 1, 'airdate' => '2016-04-08'],
            ['title' => "Full Moon (天満月 Amamitsuki)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 2, 'airdate' => '2016-04-15'],
            ['title' => "Villains/Prescription (悪党／処方箋 Akutō / Shohōsen)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 3, 'airdate' => '2016-04-22'],
            ['title' => "Stranger (異邦人 Ihōjin)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 4, 'airdate' => '2016-04-29'],
            ['title' => "Chivalry (騎士道 Kishidō)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 5, 'airdate' => '2016-05-06'],
            ['title' => "Rootless Plants (根無草 Nenashigusa)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 6, 'airdate' => '2016-05-13'],
            ['title' => "Transfer Student (転校生 Tenkōsei)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 7, 'airdate' => '2016-05-20'],
            ['title' => "Pipe Dream/Touchstone (白昼夢／試金石 Hakuchūmu / Shikinseki)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 8, 'airdate' => '2016-05-27'],
            ['title' => "Greenhorn (若輩者 Jakuhai-mono)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 9, 'airdate' => '2016-06-03'],
            ['title' => "Unprecedented (破天荒 Hatenkō)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 10, 'airdate' => '2016-06-10'],
            ['title' => "Sunlight and Shadow (陰日向 Kagehinata)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 11, 'airdate' => '2016-06-17'],
            ['title' => "Golden Monument (金字塔 Kinjitō)", 'category_id' => $this->Category('makai-retsuden'), 'type' => 'episode', 'number' => 12, 'airdate' => '2016-06-24'],
            ['title' => "Silver Wolf (銀狼 Ginrō)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 1, 'airdate' => '2017-01-06'],
            ['title' => "Dancing Girl (舞姫 Maihime)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 2, 'airdate' => '2017-01-13'],
            ['title' => "Pistol (拳銃 Kenjū)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 3, 'airdate' => '2017-01-20'],
            ['title' => "Dragon-Man (竜人 Ryūjin)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 4, 'airdate' => '2017-01-27'],
            ['title' => "Eternity (永遠 Eien)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 5, 'airdate' => '2017-02-03'],
            ['title' => "Kagome (籠目 Kagome)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 6, 'airdate' => '2017-02-10'],
            ['title' => "Twin Swords (双剣 Sōken)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 7, 'airdate' => '2017-02-17'],
            ['title' => "Photograph (写真 Shashin)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 8, 'airdate' => '2017-02-24'],
            ['title' => "Motherliness (母性 Bosei)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 9, 'airdate' => '2017-03-03'],
            ['title' => "Legend (伝説 Densetsu)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 10, 'airdate' => '2017-03-10'],
            ['title' => "Temple (神殿 Shinden)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 11, 'airdate' => '2017-03-17'],
            ['title' => "Smile (微笑 Bishō)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 12, 'airdate' => '2017-03-24'],
            ['title' => "World (世界 Sekai)", 'category_id' => $this->Category('zero-dragon-blood'), 'type' => 'episode', 'number' => 13, 'airdate' => '2017-03-31'],
            ['title' => "Destruction / Rebirth (消滅／再生 Shōmetsu / Saisei)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 1, 'airdate' => '2018-10-11'],
            ['title' => "Despair / Hope (絶望／希望 Zetsubō / Kibō)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 2, 'airdate' => '2018-10-18'],
            ['title' => "Determination / Malice (決意／悪意 Ketsui / Akui)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 3, 'airdate' => '2018-10-25'],
            ['title' => "Doubts / Awakening (疑念／目覚 Ginen / Mezame)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 4, 'airdate' => '2018-11-01'],
            ['title' => "Stupor / Teaching (混迷／教示 Konmei / Kyōji)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 5, 'airdate' => '2018-11-08'],
            ['title' => "Outside / Inside (表／裏 Omote / Ura)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 6, 'airdate' => '2018-11-15'],
            ['title' => "Bonds / Breaking (絆／断 Kizuna / Dan)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 7, 'airdate' => '2018-11-22'],
            ['title' => "Blind Faith / Doubts (盲信／懐疑 Mōshin / Kaigi)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 8, 'airdate' => '2018-11-29'],
            ['title' => "No Beginning / No End (無始／無終 Mushi / Mujū)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 9, 'airdate' => '2018-12-06'],
            ['title' => "Self-Conceit / Predicament (独尊／窮地 Dokuson / Kyūchi)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 10, 'airdate' => '2018-12-13'],
            ['title' => "Just Cause of Fiction / Truth of Reality (虚構の大義／事実の真理 Kyokō no Taigi / Jijitsu no Shinri)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 11, 'airdate' => '2018-12-20'],
            ['title' => "Demise / Genesis (終焉／創成 Shūen / Sōsei)", 'category_id' => $this->Category('kami-no-kiba-jinga'), 'type' => 'episode', 'number' => 12, 'airdate' => '2018-12-27'],
            ['title' => 'Prologue (序章 Joshō)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 1, 'airdate' => '2024-01-11'],
            ['title' => 'Symptoms (症状 Shōjō)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 2, 'airdate' => '2024-01-18'],
            ['title' => 'Hagane (鋼 Hagane)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 3, 'airdate' => '2024-01-25'],
            ['title' => 'Scar (傷跡 Kizuato)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 4, 'airdate' => '2024-02-01'],
            ['title' => 'Realize (覚醒 Kakusei)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 5, 'airdate' => '2024-02-08'],
            ['title' => 'Eyes (眼差し Manazashi)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 6, 'airdate' => '2024-02-15'],
            ['title' => 'Tragedy (悲劇 Higeki)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 7, 'airdate' => '2024-02-22'],
            ['title' => 'Flash (閃光 Senkō)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 8, 'airdate' => '2024-02-29'],
            ['title' => 'Gate (門 Mon)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 9, 'airdate' => '2024-03-07'],
            ['title' => 'Deception (欺瞞 Giman)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 10, 'airdate' => '2024-03-14'],
            ['title' => 'Invitation (招待 Shōtai)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 11, 'airdate' => '2024-03-21'],
            ['title' => 'Inherit (継承 Keishō)', 'category_id' => $this->Category('hagane-o-tsugu-mono'), 'type' => 'episode', 'number' => 12, 'airdate' => '2024-03-28'],

        ])->map(function ($item) use ($timestamp) {

            $category = Category::find($item['category_id']);

            $item['slug'] = \Illuminate\Support\Str::slug(
                "{$category->fullname} {$item['type']} {$item['number']}"
            );

            return array_merge($item, $timestamp);
        });

        DB::table('videos')->insert($data->toArray());
    }

    private function Category(string $slug): string
    {
        $category = Category::where('slug', $slug)->first();
        if (!$category) {
            $category = Category::create([
                'slug' => $slug,
            ]);
        }
        return $category->id;
    }
}
