@BASE_URL = http://127.0.0.1:8000/api
@user_id = 1
@franchise_id = 2
@era_id = 3
@category_id = 4
@data_id = 5
@tag_id = 6
@auth_token = token

### Login (Get Token)
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "password"
}

### Logout (Revoke Token)
POST {{BASE_URL}}/auth/logout
Authorization: Bearer {{auth_token}}

### Get List of Data
GET {{BASE_URL}}/datas
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Single Data by ID
GET {{BASE_URL}}/datas/{{data_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create New Data
POST {{BASE_URL}}/datas
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "New Data Example",
  "category_id": {{category_id}},
  "tags": [{{tag_id}}]
}

### Update Data
PUT {{BASE_URL}}/datas/{{data_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Updated Data Example",
  "category_id": {{category_id}},
  "tags": [{{tag_id}}]
}

### Delete Data
DELETE {{BASE_URL}}/datas/{{data_id}}
Authorization: Bearer {{auth_token}}

### Get List of Franchises
GET {{BASE_URL}}/franchises
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Single Franchise by ID
GET {{BASE_URL}}/franchises/{{franchise_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create New Franchise
POST {{BASE_URL}}/franchises
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "New Franchise Example"
}

### Update Franchise
PUT {{BASE_URL}}/franchises/{{franchise_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Updated Franchise Example"
}

### Delete Franchise
DELETE {{BASE_URL}}/franchises/{{franchise_id}}
Authorization: Bearer {{auth_token}}

### Get List of Eras
GET {{BASE_URL}}/eras
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Single Era by ID
GET {{BASE_URL}}/eras/{{era_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create New Era
POST {{BASE_URL}}/eras
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "New Era Example"
}

### Update Era
PUT {{BASE_URL}}/eras/{{era_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Updated Era Example"
}

### Delete Era
DELETE {{BASE_URL}}/eras/{{era_id}}
Authorization: Bearer {{auth_token}}

### Get List of Categories
GET {{BASE_URL}}/categories
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Single Category by ID
GET {{BASE_URL}}/categories/{{category_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create New Category
POST {{BASE_URL}}/categories
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "era_id": "{{era_id}}",
  "franchise_id": "{{franchise_id}}",
  "name": "New Category Example"
}

### Update Category
PUT {{BASE_URL}}/categories/{{category_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "era_id": "{{era_id}}",
  "franchise_id": "{{franchise_id}}",
  "name": "Updated Category Example"
}

### Delete Category
DELETE {{BASE_URL}}/categories/{{category_id}}
Authorization: Bearer {{auth_token}}

### Get List of Tags
GET {{BASE_URL}}/tags
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Single Tag by ID
GET {{BASE_URL}}/tags/{{tag_id}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create New Tag
POST {{BASE_URL}}/tags
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "New Tag Example"
}

### Update Tag
PUT {{BASE_URL}}/tags/{{tag_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Updated Tag Example"
}

### Delete Tag
DELETE {{BASE_URL}}/tags/{{tag_id}}
Authorization: Bearer {{auth_token}}

### Get List of Users
GET {{BASE_URL}}/users
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create New User
POST {{BASE_URL}}/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "New User Example",
  "email": "user@example.com",
  "password": "password"
}

### Update User
PUT {{BASE_URL}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Admin Update",
  "email": "admin@admin.com"
}

### Delete User
DELETE {{BASE_URL}}/users/{{user_id}}
Authorization: Bearer {{auth_token}}
